# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
# app/config/config.yml
fos_ck_editor:
    input_sync: true
    default_config: base_config
    base_path: "build/ckeditor"
    js_path:   "build/ckeditor/ckeditor.js"
    configs:
        base_config:
            toolbar:
              
        my_config:
            toolbar: full
