controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
# config/routes.yaml
app_home:
    path: /
    controller: App\Controller\HomeController::index
